# Generated by Django 5.2.1 on 2025-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'Debet'), ('CREDIT', 'Kredyt')], default='DEBIT', max_length=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Aktywa'), ('LIABILITY', 'Pasywa - Zobowiązania i rezerwy na zobowiązania'), ('EQUITY', 'Pasywa - Kapitał własny'), ('EXPENSE', 'Koszty'), ('REVENUE', 'Przychody')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
