# Generated by Django 5.2.1 on 2025-06-11 05:06

from django.db import migrations


def create_initial_accounts(apps, schema_editor):
    Account = apps.get_model('accounting_app', 'Account')
    accounts_data = [
        {'name': 'Urządzenia techniczne i maszyny', 'account_type': 'ASSET', 'normal_balance': 'DEBIT'},
        {'name': 'Umorzenie urządzeń technicznych i maszyn', 'account_type': 'ASSET', 'normal_balance': 'CREDIT'},
        {'name': 'Środki transportu', 'account_type': 'ASSET', 'normal_balance': 'DEBIT'},
        {'name': 'Umorzenie środków transportu', 'account_type': 'ASSET', 'normal_balance': 'CREDIT'},
        {'name': 'Należności z tytułu dostaw i usług od pozostałych jednostek do 12 m-cy', 'account_type': 'ASSET', 'normal_balance': 'DEBIT'},
        {'name': 'Środki pieniężne w kasie', 'account_type': 'ASSET', 'normal_balance': 'DEBIT'},
        {'name': 'Środki pieniężne na r-kach bankowych', 'account_type': 'ASSET', 'normal_balance': 'DEBIT'},
        {'name': 'Kapitał (fundusz) podstawowy', 'account_type': 'EQUITY', 'normal_balance': 'CREDIT'},
        {'name': 'Zysk (strata) netto', 'account_type': 'EQUITY', 'normal_balance': 'CREDIT'},
        {'name': 'Zobowiązania z tytułu dostaw i usług wobec pozostałych jednostek do 12 m-cy', 'account_type': 'LIABILITY', 'normal_balance': 'CREDIT'},
        {'name': 'Kredyty bankowe krótkoterminowe', 'account_type': 'LIABILITY', 'normal_balance': 'CREDIT'},
        {'name': 'Zobowiązania z tytułu wynagrodzeń', 'account_type': 'LIABILITY', 'normal_balance': 'CREDIT'},
        {'name': 'Zobowiązania z tytułu publicznoprawnych', 'account_type': 'LIABILITY', 'normal_balance': 'CREDIT'},
        {'name': 'Amortyzacja', 'account_type': 'EXPENSE', 'normal_balance': 'DEBIT'},
    ]
    for acc_data in accounts_data:
        account, created = Account.objects.get_or_create(
            name=acc_data['name'],
            defaults={
                'account_type': acc_data['account_type'],
                'normal_balance': acc_data['normal_balance']
            }
        )
        if not created:
            account.account_type = acc_data['account_type']
            account.normal_balance = acc_data['normal_balance']
            account.save()


def remove_initial_accounts(apps, schema_editor):
    Account = apps.get_model('accounting_app', 'Account')
    account_names = [
        'Urządzenia techniczne i maszyny',
        'Umorzenie urządzeń technicznych i maszyn',
        'Środki transportu',
        'Umorzenie środków transportu',
        'Należności z tytułu dostaw i usług od pozostałych jednostek do 12 m-cy',
        'Środki pieniężne w kasie',
        'Środki pieniężne na r-kach bankowych',
        'Kapitał (fundusz) podstawowy',
        'Zysk (strata) netto',
        'Zobowiązania z tytułu dostaw i usług wobec pozostałych jednostek do 12 m-cy',
        'Kredyty bankowe krótkoterminowe',
        'Zobowiązania z tytułu wynagrodzeń',
        'Zobowiązania z tytułu publicznoprawnych',
        'Amortyzacja',
    ]
    Account.objects.filter(name__in=account_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_account_normal_balance_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_accounts, reverse_code=remove_initial_accounts),
    ]